name: Run moboFetcher ON KOYEB (defunct)

on:
  # schedule:
  #   - cron: "0 3 * * 3" # (This will trigger at 3:00 AM UTC every Wednesday.)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  trigger-moboFetcher:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger moboFetcher ON KOYEB
        run: |
          curl -X POST https://asrockbioschecker.koyeb.app/trigger \
            -H "Content-Type: application/json" \
            --data "{\"secret\": \"${{ secrets.KOYEB_REPOPUSHKEY }}\", \"task\": \"moboFetcher\"}"

      - name: Notify success
        if: success()
        run: echo "moboFetcher triggered successfully on Koyeb!"

      - name: Notify failure
        if: failure()
        run: echo "Failed to trigger moboFetcher on Koyeb."
