name: Run moboFetcher Task (weekly)

on:
  schedule:
    - cron: '0 3 * * 3' # (This will trigger at 3:00 AM UTC every Wednesday.)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your app requires

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the tasks
      - name: Run moboFetcher task
        run: node ../../public/js/moboFetcher.js

      # Optional: Notify on workflow success
      - name: Notify success
        if: success()
        run: echo "Scheduled task ran successfully!"

      # Optional: Notify on workflow failure
      - name: Notify failure
        if: failure()
        run: echo "Scheduled task failed to complete."
